# NumPy Exercises 

Write the code for the following questions in the space provided and submit the .ipynb files on Nalanda

#### Q 1: Import NumPy as np

In [1]:
import numpy as np

#### Q 2: Create an array of 10 zeros 

In [15]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Q 3: Create an array of 10 ones

In [13]:
a = np.ones(10)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Q 4: Create an array of 10 fives

In [19]:
a = 5 * np.ones(10)
a

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Q 5: Create an array of the integers from 10 to 50

In [22]:
b = np.arange(10,51,1)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Q 6: Create an array of all the even integers from 10 to 50

In [23]:
b = np.arange(10,51,2)
b

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Q 7: Create a 3x3 matrix with values ranging from 0 to 8

In [27]:
c = np.array([
    [0,1,2],
    [3,4,5],
    [6,7,8]
    
])
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Q 8: Create a 3x3 identity matrix

In [29]:
a = np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### Q 9: Use NumPy to generate a random number between 0 and 1

In [104]:
num = np.random.rand(1)
num

array([0.3406039])

#### Q 10: Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [105]:
a = np.random.normal(0,1,25)
a

array([-0.29790232, -1.87207741, -2.26125084, -1.30560006,  1.74152624,
        1.90014942,  2.15886223,  0.78190303,  0.09004954,  1.11161661,
       -0.42151065, -1.39447297, -0.26535237,  1.89987554,  0.23799535,
        0.21619541, -0.2771642 ,  1.08547291,  1.10567848,  1.5012041 ,
       -0.7620117 ,  0.84395081, -0.15129752, -0.42112558,  1.25327817])

#### Create the following matrix:

#### Q 11: Create an array of 20 linearly spaced points between 0 and 1:

In [43]:
a = np.linspace(0,1,20)
a
    

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection
Write the code to produce the given outputs using the matrix "mat" 

In [82]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [87]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
mat1 = mat[2:,1:]
mat1

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [88]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
mat[3][4]

20

In [106]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
mat2 = mat[:3,1:2]
mat2

array([[ 2],
       [ 7],
       [12]])

In [107]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
a = mat[4,:]
a

array([21, 22, 23, 24, 25])

In [94]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
mat4= mat[3:5,:]
mat4

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### Get the sum of all the values in mat

In [95]:
mat.sum()

325

#### Get the standard deviation of the values in mat

In [96]:
np.std(mat)

7.211102550927978

#### Get the sum of all the columns in mat

In [97]:
mat.sum(axis= 0)

array([55, 60, 65, 70, 75])